[package]
name = "database-server"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
actix-web = "4.11.0"
shared = { path = "../shared" }
openssl = { version = "0.10", features = ["vendored"] }
